---
abstract: 'Independently access radio network modems (such as 3GPP)'
author:
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::More: 0.90
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Radio-Modem
provides:
  Net::Radio::Modem:
    file: lib/Net/Radio/Modem.pm
    version: 0.002
  Net::Radio::Modem::Adapter:
    file: lib/Net/Radio/Modem/Adapter.pm
    version: 0.002
  Net::Radio::Modem::Adapter::Null:
    file: lib/Net/Radio/Modem/Adapter/Null.pm
    version: 0.002
  Net::Radio::Modem::Adapter::Static:
    file: lib/Net/Radio/Modem/Adapter/Static.pm
    version: 0.002
requires:
  perl: 5.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
